// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelTakipSistemi.Data;

#nullable disable

namespace PersonelTakipSistemi.Migrations
{
    [DbContext(typeof(TegmPersonelTakipDbContext))]
    [Migration("20260112113919_SetVedatAdmin")]
    partial class SetVedatAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelTakipSistemi.Models.Brans", b =>
                {
                    b.Property<int>("BransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BransId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("BransId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Branslar", (string)null);

                    b.HasData(
                        new
                        {
                            BransId = 1,
                            Ad = "Adalet"
                        },
                        new
                        {
                            BransId = 2,
                            Ad = "Aile ve Tüketici Hizmetleri"
                        },
                        new
                        {
                            BransId = 3,
                            Ad = "Almanca"
                        },
                        new
                        {
                            BransId = 4,
                            Ad = "Arapça"
                        },
                        new
                        {
                            BransId = 5,
                            Ad = "Ayakkabı ve Saraciye Teknolojisi"
                        },
                        new
                        {
                            BransId = 6,
                            Ad = "Beden Eğitimi"
                        },
                        new
                        {
                            BransId = 7,
                            Ad = "Bilgisayar ve Öğretim Teknolojileri"
                        },
                        new
                        {
                            BransId = 8,
                            Ad = "Bilişim Teknolojileri"
                        },
                        new
                        {
                            BransId = 9,
                            Ad = "Biyoloji"
                        },
                        new
                        {
                            BransId = 10,
                            Ad = "Büro Yönetimi / Büro Yönetimi ve Yönetici Asistanlığı"
                        },
                        new
                        {
                            BransId = 11,
                            Ad = "Coğrafya"
                        },
                        new
                        {
                            BransId = 12,
                            Ad = "Çocuk Gelişimi ve Eğitimi"
                        },
                        new
                        {
                            BransId = 13,
                            Ad = "Denizcilik / Gemi Makineleri"
                        },
                        new
                        {
                            BransId = 14,
                            Ad = "Denizcilik / Gemi Yönetimi"
                        },
                        new
                        {
                            BransId = 15,
                            Ad = "Din Kültürü ve Ahlâk Bilgisi"
                        },
                        new
                        {
                            BransId = 16,
                            Ad = "El Sanatları Teknolojisi / El Sanatları"
                        },
                        new
                        {
                            BransId = 17,
                            Ad = "El Sanatları Teknolojisi / Nakış"
                        },
                        new
                        {
                            BransId = 18,
                            Ad = "Elektrik-Elektronik Teknolojisi / Elektrik"
                        },
                        new
                        {
                            BransId = 19,
                            Ad = "Elektrik-Elektronik Teknolojisi / Elektronik"
                        },
                        new
                        {
                            BransId = 20,
                            Ad = "Endüstriyel Otomasyon Teknolojileri"
                        },
                        new
                        {
                            BransId = 21,
                            Ad = "Farsça"
                        },
                        new
                        {
                            BransId = 22,
                            Ad = "Felsefe"
                        },
                        new
                        {
                            BransId = 23,
                            Ad = "Fen Bilimleri"
                        },
                        new
                        {
                            BransId = 24,
                            Ad = "Fizik"
                        },
                        new
                        {
                            BransId = 25,
                            Ad = "Gemi Yapımı / Yat İnşa"
                        },
                        new
                        {
                            BransId = 26,
                            Ad = "Gıda Teknolojisi"
                        },
                        new
                        {
                            BransId = 27,
                            Ad = "Giyim Üretim Teknolojisi / Moda Tasarım Teknolojileri"
                        },
                        new
                        {
                            BransId = 28,
                            Ad = "Görsel Sanatlar"
                        },
                        new
                        {
                            BransId = 29,
                            Ad = "Grafik ve Fotoğraf / Grafik"
                        },
                        new
                        {
                            BransId = 30,
                            Ad = "Harita-Tapu-Kadastro / Harita Kadastro"
                        },
                        new
                        {
                            BransId = 31,
                            Ad = "Hasta ve Yaşlı Hizmetleri"
                        },
                        new
                        {
                            BransId = 32,
                            Ad = "Hayvan Sağlığı / Hayvan Yetiştiriciliği ve Sağlığı / Hayvan Sağlığı"
                        },
                        new
                        {
                            BransId = 33,
                            Ad = "Hayvan Sağlığı / Hayvan Yetiştiriciliği ve Sağlığı / Hayvan Yetiştiriciliği"
                        },
                        new
                        {
                            BransId = 34,
                            Ad = "İlköğretim Matematik"
                        },
                        new
                        {
                            BransId = 35,
                            Ad = "İmam-Hatip Lisesi Meslek Dersleri"
                        },
                        new
                        {
                            BransId = 36,
                            Ad = "İngilizce"
                        },
                        new
                        {
                            BransId = 37,
                            Ad = "İnşaat Teknolojisi / Yapı Dekorasyon"
                        },
                        new
                        {
                            BransId = 38,
                            Ad = "İnşaat Teknolojisi / Yapı Tasarım"
                        },
                        new
                        {
                            BransId = 39,
                            Ad = "İtfaiyecilik ve Yangın Güvenliği"
                        },
                        new
                        {
                            BransId = 40,
                            Ad = "Kimya / Kimya Teknolojisi"
                        },
                        new
                        {
                            BransId = 41,
                            Ad = "Konaklama ve Seyahat Hizmetleri / Konaklama ve Seyahat"
                        },
                        new
                        {
                            BransId = 42,
                            Ad = "Kuyumculuk Teknolojisi"
                        },
                        new
                        {
                            BransId = 43,
                            Ad = "Makine Teknolojisi / Makine ve Tasarım Teknolojisi / Makine Model"
                        },
                        new
                        {
                            BransId = 44,
                            Ad = "Makine Teknolojisi / Makine ve Tasarım Teknolojisi / Makine Ressamlığı"
                        },
                        new
                        {
                            BransId = 45,
                            Ad = "Makine Teknolojisi / Makine ve Tasarım Teknolojisi / Makine ve Kalıp"
                        },
                        new
                        {
                            BransId = 46,
                            Ad = "Matbaa / Matbaa Teknolojisi"
                        },
                        new
                        {
                            BransId = 47,
                            Ad = "Matematik"
                        },
                        new
                        {
                            BransId = 48,
                            Ad = "Metal Teknolojisi"
                        },
                        new
                        {
                            BransId = 49,
                            Ad = "Mobilya ve İç Mekan Tasarımı"
                        },
                        new
                        {
                            BransId = 50,
                            Ad = "Motorlu Araçlar Teknolojisi"
                        },
                        new
                        {
                            BransId = 51,
                            Ad = "Muhasebe ve Finansman"
                        },
                        new
                        {
                            BransId = 52,
                            Ad = "Müzik"
                        },
                        new
                        {
                            BransId = 53,
                            Ad = "Okul Öncesi"
                        },
                        new
                        {
                            BransId = 54,
                            Ad = "Özel Eğitim"
                        },
                        new
                        {
                            BransId = 55,
                            Ad = "Pazarlama ve Perakende"
                        },
                        new
                        {
                            BransId = 56,
                            Ad = "Plastik Teknolojisi"
                        },
                        new
                        {
                            BransId = 57,
                            Ad = "Raylı Sistemler Teknolojisi / Raylı Sistemler Elektrik-Elektronik"
                        },
                        new
                        {
                            BransId = 58,
                            Ad = "Rehberlik"
                        },
                        new
                        {
                            BransId = 59,
                            Ad = "Rusça"
                        },
                        new
                        {
                            BransId = 60,
                            Ad = "Sağlık / Sağlık Hizmetleri"
                        },
                        new
                        {
                            BransId = 61,
                            Ad = "Sağlık Bilgisi"
                        },
                        new
                        {
                            BransId = 62,
                            Ad = "Seramik ve Cam Teknolojisi"
                        },
                        new
                        {
                            BransId = 63,
                            Ad = "Sınıf Öğretmenliği"
                        },
                        new
                        {
                            BransId = 64,
                            Ad = "Sosyal Bilgiler"
                        },
                        new
                        {
                            BransId = 65,
                            Ad = "Tarım Teknolojileri/Tarım"
                        },
                        new
                        {
                            BransId = 66,
                            Ad = "Tarih"
                        },
                        new
                        {
                            BransId = 67,
                            Ad = "Teknoloji ve Tasarım"
                        },
                        new
                        {
                            BransId = 68,
                            Ad = "Tesisat Teknolojisi ve İklimlendirme"
                        },
                        new
                        {
                            BransId = 69,
                            Ad = "Tiyatro"
                        },
                        new
                        {
                            BransId = 70,
                            Ad = "Türk Dili ve Edebiyatı"
                        },
                        new
                        {
                            BransId = 71,
                            Ad = "Türkçe"
                        },
                        new
                        {
                            BransId = 72,
                            Ad = "Ulaştırma Hizmetleri / Lojistik"
                        },
                        new
                        {
                            BransId = 73,
                            Ad = "Yaşayan Diller ve Lehçeler (Kürtçe / Kurmançi)"
                        },
                        new
                        {
                            BransId = 74,
                            Ad = "Yaşayan Diller ve Lehçeler (Kürtçe / Zazaki)"
                        },
                        new
                        {
                            BransId = 75,
                            Ad = "Yenilenebilir Enerji Teknolojileri"
                        },
                        new
                        {
                            BransId = 76,
                            Ad = "Yiyecek İçecek Hizmetleri"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Property<int>("GorevTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevTuruId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GorevTuruId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("GorevTurleri", (string)null);

                    b.HasData(
                        new
                        {
                            GorevTuruId = 1,
                            Ad = "Dizgi"
                        },
                        new
                        {
                            GorevTuruId = 2,
                            Ad = "Görsel Üretim"
                        },
                        new
                        {
                            GorevTuruId = 3,
                            Ad = "Çizer"
                        },
                        new
                        {
                            GorevTuruId = 4,
                            Ad = "Çizgi Roman Renklendirme"
                        },
                        new
                        {
                            GorevTuruId = 5,
                            Ad = "Görsel Kontrolü"
                        },
                        new
                        {
                            GorevTuruId = 6,
                            Ad = "Çoklu Ortam Tasarımı"
                        },
                        new
                        {
                            GorevTuruId = 7,
                            Ad = "Video/Kurgu"
                        },
                        new
                        {
                            GorevTuruId = 8,
                            Ad = "Fotoğraf Çekimi"
                        },
                        new
                        {
                            GorevTuruId = 9,
                            Ad = "Açıklama"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Il", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IlId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Iller", (string)null);

                    b.HasData(
                        new
                        {
                            IlId = 1,
                            Ad = "Adana"
                        },
                        new
                        {
                            IlId = 2,
                            Ad = "Adıyaman"
                        },
                        new
                        {
                            IlId = 3,
                            Ad = "Afyonkarahisar"
                        },
                        new
                        {
                            IlId = 4,
                            Ad = "Ağrı"
                        },
                        new
                        {
                            IlId = 5,
                            Ad = "Amasya"
                        },
                        new
                        {
                            IlId = 6,
                            Ad = "Ankara"
                        },
                        new
                        {
                            IlId = 7,
                            Ad = "Antalya"
                        },
                        new
                        {
                            IlId = 8,
                            Ad = "Artvin"
                        },
                        new
                        {
                            IlId = 9,
                            Ad = "Aydın"
                        },
                        new
                        {
                            IlId = 10,
                            Ad = "Balıkesir"
                        },
                        new
                        {
                            IlId = 11,
                            Ad = "Bilecik"
                        },
                        new
                        {
                            IlId = 12,
                            Ad = "Bingöl"
                        },
                        new
                        {
                            IlId = 13,
                            Ad = "Bitlis"
                        },
                        new
                        {
                            IlId = 14,
                            Ad = "Bolu"
                        },
                        new
                        {
                            IlId = 15,
                            Ad = "Burdur"
                        },
                        new
                        {
                            IlId = 16,
                            Ad = "Bursa"
                        },
                        new
                        {
                            IlId = 17,
                            Ad = "Çanakkale"
                        },
                        new
                        {
                            IlId = 18,
                            Ad = "Çankırı"
                        },
                        new
                        {
                            IlId = 19,
                            Ad = "Çorum"
                        },
                        new
                        {
                            IlId = 20,
                            Ad = "Denizli"
                        },
                        new
                        {
                            IlId = 21,
                            Ad = "Diyarbakır"
                        },
                        new
                        {
                            IlId = 22,
                            Ad = "Edirne"
                        },
                        new
                        {
                            IlId = 23,
                            Ad = "Elazığ"
                        },
                        new
                        {
                            IlId = 24,
                            Ad = "Erzincan"
                        },
                        new
                        {
                            IlId = 25,
                            Ad = "Erzurum"
                        },
                        new
                        {
                            IlId = 26,
                            Ad = "Eskişehir"
                        },
                        new
                        {
                            IlId = 27,
                            Ad = "Gaziantep"
                        },
                        new
                        {
                            IlId = 28,
                            Ad = "Giresun"
                        },
                        new
                        {
                            IlId = 29,
                            Ad = "Gümüşhane"
                        },
                        new
                        {
                            IlId = 30,
                            Ad = "Hakkari"
                        },
                        new
                        {
                            IlId = 31,
                            Ad = "Hatay"
                        },
                        new
                        {
                            IlId = 32,
                            Ad = "Isparta"
                        },
                        new
                        {
                            IlId = 33,
                            Ad = "Mersin"
                        },
                        new
                        {
                            IlId = 34,
                            Ad = "İstanbul"
                        },
                        new
                        {
                            IlId = 35,
                            Ad = "İzmir"
                        },
                        new
                        {
                            IlId = 36,
                            Ad = "Kars"
                        },
                        new
                        {
                            IlId = 37,
                            Ad = "Kastamonu"
                        },
                        new
                        {
                            IlId = 38,
                            Ad = "Kayseri"
                        },
                        new
                        {
                            IlId = 39,
                            Ad = "Kırklareli"
                        },
                        new
                        {
                            IlId = 40,
                            Ad = "Kırşehir"
                        },
                        new
                        {
                            IlId = 41,
                            Ad = "Kocaeli"
                        },
                        new
                        {
                            IlId = 42,
                            Ad = "Konya"
                        },
                        new
                        {
                            IlId = 43,
                            Ad = "Kütahya"
                        },
                        new
                        {
                            IlId = 44,
                            Ad = "Malatya"
                        },
                        new
                        {
                            IlId = 45,
                            Ad = "Manisa"
                        },
                        new
                        {
                            IlId = 46,
                            Ad = "Kahramanmaraş"
                        },
                        new
                        {
                            IlId = 47,
                            Ad = "Mardin"
                        },
                        new
                        {
                            IlId = 48,
                            Ad = "Muğla"
                        },
                        new
                        {
                            IlId = 49,
                            Ad = "Muş"
                        },
                        new
                        {
                            IlId = 50,
                            Ad = "Nevşehir"
                        },
                        new
                        {
                            IlId = 51,
                            Ad = "Niğde"
                        },
                        new
                        {
                            IlId = 52,
                            Ad = "Ordu"
                        },
                        new
                        {
                            IlId = 53,
                            Ad = "Rize"
                        },
                        new
                        {
                            IlId = 54,
                            Ad = "Sakarya"
                        },
                        new
                        {
                            IlId = 55,
                            Ad = "Samsun"
                        },
                        new
                        {
                            IlId = 56,
                            Ad = "Siirt"
                        },
                        new
                        {
                            IlId = 57,
                            Ad = "Sinop"
                        },
                        new
                        {
                            IlId = 58,
                            Ad = "Sivas"
                        },
                        new
                        {
                            IlId = 59,
                            Ad = "Tekirdağ"
                        },
                        new
                        {
                            IlId = 60,
                            Ad = "Tokat"
                        },
                        new
                        {
                            IlId = 61,
                            Ad = "Trabzon"
                        },
                        new
                        {
                            IlId = 62,
                            Ad = "Tunceli"
                        },
                        new
                        {
                            IlId = 63,
                            Ad = "Şanlıurfa"
                        },
                        new
                        {
                            IlId = 64,
                            Ad = "Uşak"
                        },
                        new
                        {
                            IlId = 65,
                            Ad = "Van"
                        },
                        new
                        {
                            IlId = 66,
                            Ad = "Yozgat"
                        },
                        new
                        {
                            IlId = 67,
                            Ad = "Zonguldak"
                        },
                        new
                        {
                            IlId = 68,
                            Ad = "Aksaray"
                        },
                        new
                        {
                            IlId = 69,
                            Ad = "Bayburt"
                        },
                        new
                        {
                            IlId = 70,
                            Ad = "Karaman"
                        },
                        new
                        {
                            IlId = 71,
                            Ad = "Kırıkkale"
                        },
                        new
                        {
                            IlId = 72,
                            Ad = "Batman"
                        },
                        new
                        {
                            IlId = 73,
                            Ad = "Şırnak"
                        },
                        new
                        {
                            IlId = 74,
                            Ad = "Bartın"
                        },
                        new
                        {
                            IlId = 75,
                            Ad = "Ardahan"
                        },
                        new
                        {
                            IlId = 76,
                            Ad = "Iğdır"
                        },
                        new
                        {
                            IlId = 77,
                            Ad = "Yalova"
                        },
                        new
                        {
                            IlId = 78,
                            Ad = "Karabük"
                        },
                        new
                        {
                            IlId = 79,
                            Ad = "Kilis"
                        },
                        new
                        {
                            IlId = 80,
                            Ad = "Osmaniye"
                        },
                        new
                        {
                            IlId = 81,
                            Ad = "Düzce"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Property<int>("IsNiteligiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsNiteligiId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IsNiteligiId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("IsNitelikleri", (string)null);

                    b.HasData(
                        new
                        {
                            IsNiteligiId = 1,
                            Ad = "Ders Kitabı"
                        },
                        new
                        {
                            IsNiteligiId = 2,
                            Ad = "Çalışma Kitabı"
                        },
                        new
                        {
                            IsNiteligiId = 3,
                            Ad = "Hikâye Kitabı"
                        },
                        new
                        {
                            IsNiteligiId = 4,
                            Ad = "Çizgi Roman"
                        },
                        new
                        {
                            IsNiteligiId = 5,
                            Ad = "Çoklu Ortam"
                        },
                        new
                        {
                            IsNiteligiId = 6,
                            Ad = "MEBİ Mümtaz Şahsiyetler"
                        },
                        new
                        {
                            IsNiteligiId = 7,
                            Ad = "Dergi"
                        },
                        new
                        {
                            IsNiteligiId = 8,
                            Ad = "E Bülten"
                        },
                        new
                        {
                            IsNiteligiId = 9,
                            Ad = "E Dergi"
                        },
                        new
                        {
                            IsNiteligiId = 10,
                            Ad = "Öğretim Programı"
                        },
                        new
                        {
                            IsNiteligiId = 11,
                            Ad = "Açıklama"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Komisyon", b =>
                {
                    b.Property<int>("KomisyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomisyonId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("BaskanPersonelId")
                        .HasColumnType("int");

                    b.Property<int>("KoordinatorlukId")
                        .HasColumnType("int");

                    b.HasKey("KomisyonId");

                    b.HasIndex("BaskanPersonelId");

                    b.HasIndex("KoordinatorlukId");

                    b.ToTable("Komisyonlar", (string)null);

                    b.HasData(
                        new
                        {
                            KomisyonId = 1,
                            Ad = "Türkçe Komisyonu",
                            KoordinatorlukId = 1
                        },
                        new
                        {
                            KomisyonId = 2,
                            Ad = "Matematik Komisyonu",
                            KoordinatorlukId = 1
                        },
                        new
                        {
                            KomisyonId = 3,
                            Ad = "Fen Bilimleri Komisyonu",
                            KoordinatorlukId = 1
                        },
                        new
                        {
                            KomisyonId = 4,
                            Ad = "Türkçe Komisyonu",
                            KoordinatorlukId = 2
                        },
                        new
                        {
                            KomisyonId = 5,
                            Ad = "Matematik Komisyonu",
                            KoordinatorlukId = 2
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Koordinatorluk", b =>
                {
                    b.Property<int>("KoordinatorlukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoordinatorlukId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("BaskanPersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TeskilatId")
                        .HasColumnType("int");

                    b.HasKey("KoordinatorlukId");

                    b.HasIndex("BaskanPersonelId");

                    b.HasIndex("TeskilatId");

                    b.ToTable("Koordinatorlukler", (string)null);

                    b.HasData(
                        new
                        {
                            KoordinatorlukId = 1,
                            Ad = "Ankara TEGM Koordinatörlüğü",
                            TeskilatId = 1
                        },
                        new
                        {
                            KoordinatorlukId = 2,
                            Ad = "Mardin İl Koordinatörlüğü",
                            TeskilatId = 2
                        },
                        new
                        {
                            KoordinatorlukId = 3,
                            Ad = "İzmir İl Koordinatörlüğü",
                            TeskilatId = 2
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.KurumsalRol", b =>
                {
                    b.Property<int>("KurumsalRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KurumsalRolId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KurumsalRolId");

                    b.ToTable("KurumsalRoller", (string)null);

                    b.HasData(
                        new
                        {
                            KurumsalRolId = 1,
                            Ad = "Personel"
                        },
                        new
                        {
                            KurumsalRolId = 2,
                            Ad = "Komisyon Başkanı"
                        },
                        new
                        {
                            KurumsalRolId = 3,
                            Ad = "İl Koordinatörü"
                        },
                        new
                        {
                            KurumsalRolId = 4,
                            Ad = "Genel Koordinatör"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevliIlId")
                        .HasColumnType("int");

                    b.Property<string>("KadroKurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonelCinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SifreHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SistemRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonelId");

                    b.HasIndex("BransId");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("GorevliIlId");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("GorevTuruId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "GorevTuruId");

                    b.HasIndex("GorevTuruId");

                    b.ToTable("PersonelGorevTurleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("IsNiteligiId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "IsNiteligiId");

                    b.HasIndex("IsNiteligiId");

                    b.ToTable("PersonelIsNitelikleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKomisyon", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("KomisyonId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "KomisyonId");

                    b.HasIndex("KomisyonId");

                    b.ToTable("PersonelKomisyonlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKoordinatorluk", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("KoordinatorlukId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "KoordinatorlukId");

                    b.HasIndex("KoordinatorlukId");

                    b.ToTable("PersonelKoordinatorlukler", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKurumsalRolAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KomisyonId")
                        .HasColumnType("int");

                    b.Property<int?>("KoordinatorlukId")
                        .HasColumnType("int");

                    b.Property<int>("KurumsalRolId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KomisyonId");

                    b.HasIndex("KoordinatorlukId");

                    b.HasIndex("KurumsalRolId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelKurumsalRolAtamalari", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelTeskilat", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TeskilatId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "TeskilatId");

                    b.HasIndex("TeskilatId");

                    b.ToTable("PersonelTeskilatlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("UzmanlikId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "UzmanlikId");

                    b.HasIndex("UzmanlikId");

                    b.ToTable("PersonelUzmanliklar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("YazilimId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "YazilimId");

                    b.HasIndex("YazilimId");

                    b.ToTable("PersonelYazilimlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Teskilat", b =>
                {
                    b.Property<int>("TeskilatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeskilatId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeskilatId");

                    b.ToTable("Teskilatlar", (string)null);

                    b.HasData(
                        new
                        {
                            TeskilatId = 1,
                            Ad = "Merkez"
                        },
                        new
                        {
                            TeskilatId = 2,
                            Ad = "Taşra"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Property<int>("UzmanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzmanlikId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UzmanlikId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Uzmanliklar", (string)null);

                    b.HasData(
                        new
                        {
                            UzmanlikId = 1,
                            Ad = "Bilişim Uzmanı"
                        },
                        new
                        {
                            UzmanlikId = 2,
                            Ad = "Görsel Tasarım Uzmanı"
                        },
                        new
                        {
                            UzmanlikId = 3,
                            Ad = "Yazar"
                        },
                        new
                        {
                            UzmanlikId = 4,
                            Ad = "Dil Uzmanı"
                        },
                        new
                        {
                            UzmanlikId = 5,
                            Ad = "Rehberlik"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Property<int>("YazilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazilimId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("YazilimId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Yazilimlar", (string)null);

                    b.HasData(
                        new
                        {
                            YazilimId = 1,
                            Ad = "Photoshop"
                        },
                        new
                        {
                            YazilimId = 2,
                            Ad = "İllüstrator"
                        },
                        new
                        {
                            YazilimId = 3,
                            Ad = "InDesign"
                        },
                        new
                        {
                            YazilimId = 4,
                            Ad = "Camtasia"
                        },
                        new
                        {
                            YazilimId = 5,
                            Ad = "Premiere"
                        },
                        new
                        {
                            YazilimId = 6,
                            Ad = "After Effects"
                        },
                        new
                        {
                            YazilimId = 7,
                            Ad = "Cinema 4D"
                        },
                        new
                        {
                            YazilimId = 8,
                            Ad = "Blender"
                        },
                        new
                        {
                            YazilimId = 9,
                            Ad = "Maya"
                        },
                        new
                        {
                            YazilimId = 10,
                            Ad = "Procreate"
                        },
                        new
                        {
                            YazilimId = 11,
                            Ad = "Construct"
                        },
                        new
                        {
                            YazilimId = 12,
                            Ad = "Articulate"
                        },
                        new
                        {
                            YazilimId = 13,
                            Ad = "Unity"
                        },
                        new
                        {
                            YazilimId = 14,
                            Ad = "Unreal Engine"
                        },
                        new
                        {
                            YazilimId = 15,
                            Ad = "PHP"
                        },
                        new
                        {
                            YazilimId = 16,
                            Ad = "Java"
                        },
                        new
                        {
                            YazilimId = 17,
                            Ad = ".NET"
                        },
                        new
                        {
                            YazilimId = 18,
                            Ad = "Diğer"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Komisyon", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "BaskanPersonel")
                        .WithMany()
                        .HasForeignKey("BaskanPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonelTakipSistemi.Models.Koordinatorluk", "Koordinatorluk")
                        .WithMany("Komisyonlar")
                        .HasForeignKey("KoordinatorlukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaskanPersonel");

                    b.Navigation("Koordinatorluk");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Koordinatorluk", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "BaskanPersonel")
                        .WithMany()
                        .HasForeignKey("BaskanPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonelTakipSistemi.Models.Teskilat", "Teskilat")
                        .WithMany("Koordinatorlukler")
                        .HasForeignKey("TeskilatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaskanPersonel");

                    b.Navigation("Teskilat");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Brans", "Brans")
                        .WithMany("Personeller")
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Il", "GorevliIl")
                        .WithMany("Personeller")
                        .HasForeignKey("GorevliIlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brans");

                    b.Navigation("GorevliIl");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.GorevTuru", "GorevTuru")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("GorevTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.IsNiteligi", "IsNiteligi")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("IsNiteligiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsNiteligi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKomisyon", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Komisyon", "Komisyon")
                        .WithMany("PersonelKomisyonlar")
                        .HasForeignKey("KomisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelKomisyonlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komisyon");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKoordinatorluk", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Koordinatorluk", "Koordinatorluk")
                        .WithMany("PersonelKoordinatorlukler")
                        .HasForeignKey("KoordinatorlukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelKoordinatorlukler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koordinatorluk");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelKurumsalRolAtama", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Komisyon", "Komisyon")
                        .WithMany()
                        .HasForeignKey("KomisyonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonelTakipSistemi.Models.Koordinatorluk", "Koordinatorluk")
                        .WithMany()
                        .HasForeignKey("KoordinatorlukId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonelTakipSistemi.Models.KurumsalRol", "KurumsalRol")
                        .WithMany()
                        .HasForeignKey("KurumsalRolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelKurumsalRolAtamalari")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komisyon");

                    b.Navigation("Koordinatorluk");

                    b.Navigation("KurumsalRol");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelTeskilat", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelTeskilatlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Teskilat", "Teskilat")
                        .WithMany("PersonelTeskilatlar")
                        .HasForeignKey("TeskilatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Teskilat");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Uzmanlik", "Uzmanlik")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("UzmanlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Uzmanlik");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Yazilim", "Yazilim")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("YazilimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Yazilim");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Brans", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Navigation("PersonelGorevTurleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Il", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Navigation("PersonelIsNitelikleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Komisyon", b =>
                {
                    b.Navigation("PersonelKomisyonlar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Koordinatorluk", b =>
                {
                    b.Navigation("Komisyonlar");

                    b.Navigation("PersonelKoordinatorlukler");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Navigation("PersonelGorevTurleri");

                    b.Navigation("PersonelIsNitelikleri");

                    b.Navigation("PersonelKomisyonlar");

                    b.Navigation("PersonelKoordinatorlukler");

                    b.Navigation("PersonelKurumsalRolAtamalari");

                    b.Navigation("PersonelTeskilatlar");

                    b.Navigation("PersonelUzmanliklar");

                    b.Navigation("PersonelYazilimlar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Teskilat", b =>
                {
                    b.Navigation("Koordinatorlukler");

                    b.Navigation("PersonelTeskilatlar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Navigation("PersonelUzmanliklar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Navigation("PersonelYazilimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
