// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelTakipSistemi.Data;

#nullable disable

namespace PersonelTakipSistemi.Migrations
{
    [DbContext(typeof(TegmPersonelTakipDbContext))]
    [Migration("20260110130745_InitialRefactor")]
    partial class InitialRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelTakipSistemi.Models.Brans", b =>
                {
                    b.Property<int>("BransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BransId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("BransId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Branslar", (string)null);

                    b.HasData(
                        new
                        {
                            BransId = 1,
                            Ad = "Bilişim Teknolojileri"
                        },
                        new
                        {
                            BransId = 2,
                            Ad = "Matematik"
                        },
                        new
                        {
                            BransId = 3,
                            Ad = "Fen Bilimleri"
                        },
                        new
                        {
                            BransId = 4,
                            Ad = "Türkçe"
                        },
                        new
                        {
                            BransId = 5,
                            Ad = "İngilizce"
                        },
                        new
                        {
                            BransId = 6,
                            Ad = "Sosyal Bilgiler"
                        },
                        new
                        {
                            BransId = 7,
                            Ad = "Din Kültürü ve Ahlak Bilgisi"
                        },
                        new
                        {
                            BransId = 8,
                            Ad = "Görsel Sanatlar"
                        },
                        new
                        {
                            BransId = 9,
                            Ad = "Müzik"
                        },
                        new
                        {
                            BransId = 10,
                            Ad = "Beden Eğitimi"
                        },
                        new
                        {
                            BransId = 11,
                            Ad = "Okul Öncesi"
                        },
                        new
                        {
                            BransId = 12,
                            Ad = "Rehberlik"
                        },
                        new
                        {
                            BransId = 13,
                            Ad = "Sınıf Öğretmenliği"
                        },
                        new
                        {
                            BransId = 14,
                            Ad = "Diğer"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Property<int>("GorevTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevTuruId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GorevTuruId");

                    b.ToTable("GorevTurleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Il", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IlId");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Iller", (string)null);

                    b.HasData(
                        new
                        {
                            IlId = 1,
                            Ad = "Adana"
                        },
                        new
                        {
                            IlId = 2,
                            Ad = "Adıyaman"
                        },
                        new
                        {
                            IlId = 3,
                            Ad = "Afyonkarahisar"
                        },
                        new
                        {
                            IlId = 4,
                            Ad = "Ağrı"
                        },
                        new
                        {
                            IlId = 5,
                            Ad = "Amasya"
                        },
                        new
                        {
                            IlId = 6,
                            Ad = "Ankara"
                        },
                        new
                        {
                            IlId = 7,
                            Ad = "Antalya"
                        },
                        new
                        {
                            IlId = 8,
                            Ad = "Artvin"
                        },
                        new
                        {
                            IlId = 9,
                            Ad = "Aydın"
                        },
                        new
                        {
                            IlId = 10,
                            Ad = "Balıkesir"
                        },
                        new
                        {
                            IlId = 11,
                            Ad = "Bilecik"
                        },
                        new
                        {
                            IlId = 12,
                            Ad = "Bingöl"
                        },
                        new
                        {
                            IlId = 13,
                            Ad = "Bitlis"
                        },
                        new
                        {
                            IlId = 14,
                            Ad = "Bolu"
                        },
                        new
                        {
                            IlId = 15,
                            Ad = "Burdur"
                        },
                        new
                        {
                            IlId = 16,
                            Ad = "Bursa"
                        },
                        new
                        {
                            IlId = 17,
                            Ad = "Çanakkale"
                        },
                        new
                        {
                            IlId = 18,
                            Ad = "Çankırı"
                        },
                        new
                        {
                            IlId = 19,
                            Ad = "Çorum"
                        },
                        new
                        {
                            IlId = 20,
                            Ad = "Denizli"
                        },
                        new
                        {
                            IlId = 21,
                            Ad = "Diyarbakır"
                        },
                        new
                        {
                            IlId = 22,
                            Ad = "Edirne"
                        },
                        new
                        {
                            IlId = 23,
                            Ad = "Elazığ"
                        },
                        new
                        {
                            IlId = 24,
                            Ad = "Erzincan"
                        },
                        new
                        {
                            IlId = 25,
                            Ad = "Erzurum"
                        },
                        new
                        {
                            IlId = 26,
                            Ad = "Eskişehir"
                        },
                        new
                        {
                            IlId = 27,
                            Ad = "Gaziantep"
                        },
                        new
                        {
                            IlId = 28,
                            Ad = "Giresun"
                        },
                        new
                        {
                            IlId = 29,
                            Ad = "Gümüşhane"
                        },
                        new
                        {
                            IlId = 30,
                            Ad = "Hakkari"
                        },
                        new
                        {
                            IlId = 31,
                            Ad = "Hatay"
                        },
                        new
                        {
                            IlId = 32,
                            Ad = "Isparta"
                        },
                        new
                        {
                            IlId = 33,
                            Ad = "Mersin"
                        },
                        new
                        {
                            IlId = 34,
                            Ad = "İstanbul"
                        },
                        new
                        {
                            IlId = 35,
                            Ad = "İzmir"
                        },
                        new
                        {
                            IlId = 36,
                            Ad = "Kars"
                        },
                        new
                        {
                            IlId = 37,
                            Ad = "Kastamonu"
                        },
                        new
                        {
                            IlId = 38,
                            Ad = "Kayseri"
                        },
                        new
                        {
                            IlId = 39,
                            Ad = "Kırklareli"
                        },
                        new
                        {
                            IlId = 40,
                            Ad = "Kırşehir"
                        },
                        new
                        {
                            IlId = 41,
                            Ad = "Kocaeli"
                        },
                        new
                        {
                            IlId = 42,
                            Ad = "Konya"
                        },
                        new
                        {
                            IlId = 43,
                            Ad = "Kütahya"
                        },
                        new
                        {
                            IlId = 44,
                            Ad = "Malatya"
                        },
                        new
                        {
                            IlId = 45,
                            Ad = "Manisa"
                        },
                        new
                        {
                            IlId = 46,
                            Ad = "Kahramanmaraş"
                        },
                        new
                        {
                            IlId = 47,
                            Ad = "Mardin"
                        },
                        new
                        {
                            IlId = 48,
                            Ad = "Muğla"
                        },
                        new
                        {
                            IlId = 49,
                            Ad = "Muş"
                        },
                        new
                        {
                            IlId = 50,
                            Ad = "Nevşehir"
                        },
                        new
                        {
                            IlId = 51,
                            Ad = "Niğde"
                        },
                        new
                        {
                            IlId = 52,
                            Ad = "Ordu"
                        },
                        new
                        {
                            IlId = 53,
                            Ad = "Rize"
                        },
                        new
                        {
                            IlId = 54,
                            Ad = "Sakarya"
                        },
                        new
                        {
                            IlId = 55,
                            Ad = "Samsun"
                        },
                        new
                        {
                            IlId = 56,
                            Ad = "Siirt"
                        },
                        new
                        {
                            IlId = 57,
                            Ad = "Sinop"
                        },
                        new
                        {
                            IlId = 58,
                            Ad = "Sivas"
                        },
                        new
                        {
                            IlId = 59,
                            Ad = "Tekirdağ"
                        },
                        new
                        {
                            IlId = 60,
                            Ad = "Tokat"
                        },
                        new
                        {
                            IlId = 61,
                            Ad = "Trabzon"
                        },
                        new
                        {
                            IlId = 62,
                            Ad = "Tunceli"
                        },
                        new
                        {
                            IlId = 63,
                            Ad = "Şanlıurfa"
                        },
                        new
                        {
                            IlId = 64,
                            Ad = "Uşak"
                        },
                        new
                        {
                            IlId = 65,
                            Ad = "Van"
                        },
                        new
                        {
                            IlId = 66,
                            Ad = "Yozgat"
                        },
                        new
                        {
                            IlId = 67,
                            Ad = "Zonguldak"
                        },
                        new
                        {
                            IlId = 68,
                            Ad = "Aksaray"
                        },
                        new
                        {
                            IlId = 69,
                            Ad = "Bayburt"
                        },
                        new
                        {
                            IlId = 70,
                            Ad = "Karaman"
                        },
                        new
                        {
                            IlId = 71,
                            Ad = "Kırıkkale"
                        },
                        new
                        {
                            IlId = 72,
                            Ad = "Batman"
                        },
                        new
                        {
                            IlId = 73,
                            Ad = "Şırnak"
                        },
                        new
                        {
                            IlId = 74,
                            Ad = "Bartın"
                        },
                        new
                        {
                            IlId = 75,
                            Ad = "Ardahan"
                        },
                        new
                        {
                            IlId = 76,
                            Ad = "Iğdır"
                        },
                        new
                        {
                            IlId = 77,
                            Ad = "Yalova"
                        },
                        new
                        {
                            IlId = 78,
                            Ad = "Karabük"
                        },
                        new
                        {
                            IlId = 79,
                            Ad = "Kilis"
                        },
                        new
                        {
                            IlId = 80,
                            Ad = "Osmaniye"
                        },
                        new
                        {
                            IlId = 81,
                            Ad = "Düzce"
                        });
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Property<int>("IsNiteligiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsNiteligiId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IsNiteligiId");

                    b.ToTable("IsNitelikleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevliIlId")
                        .HasColumnType("int");

                    b.Property<string>("KadroKurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonelCinsiyet")
                        .HasColumnType("bit");

                    b.Property<byte[]>("SifreHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonelId");

                    b.HasIndex("BransId");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("GorevliIlId");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("GorevTuruId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "GorevTuruId");

                    b.HasIndex("GorevTuruId");

                    b.ToTable("PersonelGorevTurleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("IsNiteligiId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "IsNiteligiId");

                    b.HasIndex("IsNiteligiId");

                    b.ToTable("PersonelIsNitelikleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("UzmanlikId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "UzmanlikId");

                    b.HasIndex("UzmanlikId");

                    b.ToTable("PersonelUzmanliklar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("YazilimId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "YazilimId");

                    b.HasIndex("YazilimId");

                    b.ToTable("PersonelYazilimlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Property<int>("UzmanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzmanlikId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UzmanlikId");

                    b.ToTable("Uzmanliklar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Property<int>("YazilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazilimId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazilimId");

                    b.ToTable("Yazilimlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Brans", "Brans")
                        .WithMany("Personeller")
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Il", "GorevliIl")
                        .WithMany("Personeller")
                        .HasForeignKey("GorevliIlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brans");

                    b.Navigation("GorevliIl");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.GorevTuru", "GorevTuru")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("GorevTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.IsNiteligi", "IsNiteligi")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("IsNiteligiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsNiteligi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Uzmanlik", "Uzmanlik")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("UzmanlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Uzmanlik");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Yazilim", "Yazilim")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("YazilimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Yazilim");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Brans", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Navigation("PersonelGorevTurleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Il", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Navigation("PersonelIsNitelikleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Navigation("PersonelGorevTurleri");

                    b.Navigation("PersonelIsNitelikleri");

                    b.Navigation("PersonelUzmanliklar");

                    b.Navigation("PersonelYazilimlar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Navigation("PersonelUzmanliklar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Navigation("PersonelYazilimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
