// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelTakipSistemi.Data;

#nullable disable

namespace PersonelTakipSistemi.Migrations
{
    [DbContext(typeof(TegmPersonelTakipDbContext))]
    partial class TegmPersonelTakipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Property<int>("GorevTuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevTuruId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GorevTuruId");

                    b.ToTable("GorevTurleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Property<int>("IsNiteligiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsNiteligiId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IsNiteligiId");

                    b.ToTable("IsNitelikleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Brans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorevliIl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadroKurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelCinsiyet")
                        .HasColumnType("int");

                    b.Property<byte[]>("SifreHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonelId");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("GorevTuruId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "GorevTuruId");

                    b.HasIndex("GorevTuruId");

                    b.ToTable("PersonelGorevTurleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("IsNiteligiId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "IsNiteligiId");

                    b.HasIndex("IsNiteligiId");

                    b.ToTable("PersonelIsNitelikleri", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("UzmanlikId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "UzmanlikId");

                    b.HasIndex("UzmanlikId");

                    b.ToTable("PersonelUzmanliklar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("YazilimId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId", "YazilimId");

                    b.HasIndex("YazilimId");

                    b.ToTable("PersonelYazilimlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Property<int>("UzmanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzmanlikId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UzmanlikId");

                    b.ToTable("Uzmanliklar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Property<int>("YazilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazilimId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazilimId");

                    b.ToTable("Yazilimlar", (string)null);
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelGorevTuru", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.GorevTuru", "GorevTuru")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("GorevTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelGorevTurleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelIsNiteligi", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.IsNiteligi", "IsNiteligi")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("IsNiteligiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelIsNitelikleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsNiteligi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelUzmanlik", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Uzmanlik", "Uzmanlik")
                        .WithMany("PersonelUzmanliklar")
                        .HasForeignKey("UzmanlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Uzmanlik");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.PersonelYazilim", b =>
                {
                    b.HasOne("PersonelTakipSistemi.Models.Personel", "Personel")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonelTakipSistemi.Models.Yazilim", "Yazilim")
                        .WithMany("PersonelYazilimlar")
                        .HasForeignKey("YazilimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Yazilim");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.GorevTuru", b =>
                {
                    b.Navigation("PersonelGorevTurleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.IsNiteligi", b =>
                {
                    b.Navigation("PersonelIsNitelikleri");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Personel", b =>
                {
                    b.Navigation("PersonelGorevTurleri");

                    b.Navigation("PersonelIsNitelikleri");

                    b.Navigation("PersonelUzmanliklar");

                    b.Navigation("PersonelYazilimlar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Uzmanlik", b =>
                {
                    b.Navigation("PersonelUzmanliklar");
                });

            modelBuilder.Entity("PersonelTakipSistemi.Models.Yazilim", b =>
                {
                    b.Navigation("PersonelYazilimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
